name: Maven Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Get release tag name
        id: get_tag
        run: |
             latest_tag=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                       "https://api.github.com/repos/${{ github.repository }}/tags" \
                       | jq -r '.[0].name')
             echo "$latest_tag" > tag.txt

      - name: Build with gradle
        run: ./gradlew desktop:dist

      - name: Publish to GitHub Maven Repository
        run: |
            curl -u ${{ github.repository_owner }}:${{secrets.GITHUB_TOKEN}} -X PUT -F "file=@./desktop/build/libs/RealmTech-1.0.jar" https://maven.pkg.github.com/antoniofo/realmtech/ch/realmtech/desktop/$(cat tag.txt)/RealmTech-$(cat tag.txt).jar
