name: Maven Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Get release tag name
        id: get_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Build with gradle
        run: ./gradlew desktop:dist

      - name: Publish to GitHub Maven Repository
        run: |
            curl -u ${{secrets.USERNAME}}:${{secrets.TOKEN}} -X PUT -F "file=@./desktop/build/libs/desktop-1.0.jar" https://maven.pkg.github.com/antoniofo/realmtech/ch/realmtech/desktop/${{ steps.get_tag.outputs.tag }}/desktop-${{ steps.get_tag.outputs.tag }}.jar
